### ISSUE TITLE
About pixel warping

### ISSUE THREAD

**Issue by imbinwang** [ly015/intrinsic_flow#14]
Thanks for sharing your work. 
I am interested in the Pixel Warping(section 3.5) of your paper. As I understand, pixel warping would work when the pose does not change much, cause the visiable region of reference pose can offer some details. When the pose changes drastically, the visiable region from reference image is almost non-existent, how the details from reference image could be added to the final result as the Fig. 8 (row 2,3,4) shows?

**Comment by ly015** [comment]
Thanks for your interest. Yes, it makes sense that the pixel warping works when the pose does not change much and there is not much "unseen" region in the target image. In our experiments, we observed that the weight map in pixel warping seems more sensitive to the local pattern than to the visibility, which means it tends to add high-frequency details (e.g. texture, logo), sometimes ignore the visibility information. When the pose changes much, the pixel warping sometimes helps add plausible details to the generated image, but may also cause artifacts or unexpected results (e.g. logo in front added to the back).

**Comment by imbinwang** [comment]
Thanks for your reply.
Given a special case: a man facing us in reference image turns around in target image, the flow map generated as the gt flow map computed may lead to a horizontally flipped reference image. I think it may cause the unexpected results you mentioned. However, it may helps if the style of cloth is similar between front and back.
