### ISSUE TITLE
How to generate 3d ground truth

### ISSUE THREAD

**Issue by SeaOfOcean** [ly015/intrinsic_flow#3]
Hi, can you provide the code of generating 3d ground truth for flow map and visibility map?

**Comment by sandhyalaxmi** [comment]
you can create by
Paper: https://akanazawa.github.io/hmr/
Code:
https://github.com/akanazawa/hmr

**Comment by SeaOfOcean** [comment]
How about seg data?

**Comment by SeaOfOcean** [comment]
how to map 3d model to 2d visibility map and flow map?

**Comment by ly015** [comment]
The code for generating 3D groundtruth (SMPL), flow/visibility maps and seg data has been added at `./scripts/data_generation`. Please note that this part of codes is for reference only, which has not been cleaned and cannot be directly run. A handy script for this may be added in future updates.

We use [HMR](https://github.com/akanazawa/hmr) code for 3D human body fitting, by running `run_hmr.py` in HMR_root path. And we modified `HMR_root/src/util/renderer.py` to output visibility information when rendering the 3D human body.

`create_flow.py` is for generating flow/visibility maps from 3D models.

'create_seg.py` is for generating segmentation data, which is used in the training of the flow model. In short, the human body segmentation is obtained by clustering SMPL vertices by their most related joints (see the function: divide_vert_into_bodypart).

**Comment by longintlong** [comment]
@ly015  Thanks a lot !

**Comment by SeaOfOcean** [comment]
> The code for generating 3D groundtruth (SMPL), flow/visibility maps and seg data has been added at `./scripts/data_generation`. Please note that this part of codes is for reference only, which has not been cleaned and cannot be directly run. A handy script for this may be added in future updates.
> 
> We use [HMR](https://github.com/akanazawa/hmr) code for 3D human body fitting, by running `run_hmr.py` in HMR_root path. And we modified `HMR_root/src/util/renderer.py` to output visibility information when rendering the 3D human body.
> 
> `create_flow.py` is for generating flow/visibility maps from 3D models.
> 
> 'create_seg.py` is for generating segmentation data, which is used in the training of the flow model. In short, the human body segmentation is obtained by clustering SMPL vertices by their most related joints (see the function: divide_vert_into_bodypart).

thanks a lot. when I try to run create_flow, a issue occurs:

Traceback (most recent call last):
  File "scripts/data_generation/create_flow.py", line 6, in <module>
    from misc import flow_util
ModuleNotFoundError: No module named 'misc'

seems misc is missing

**Comment by sandhyalaxmiK** [comment]
pip install misc

**Comment by ly015** [comment]
@SeaOfOcean 
Sorry for this issue. There is a 'misc' module in the early version of the code, which has been merged into 'util'. So the flow_util can be found in the 'util' module.

As mentioned, the code in './scripts/data_generation' has not been cleaned and cannot be executed directly. Sorry again for the misleading and inconvenience.

**Comment by SeaOfOcean** [comment]
thanks @ly015 I replaced misc with util, it works fine

**Comment by xiezhy6** [comment]
Hi, how do you modify the `HMR_root/src/util/renderer.py` to output visibility information when rendering the 3D human body?

**Comment by ly015** [comment]
@xiezhy6 
Please refer to `./script/data_generation/renderer.py`.

**Comment by SeaOfOcean** [comment]
solved, thanks

**Comment by ah651** [comment]
Hi, thanks for your great work. I want to know how to generate seg labels. I read code in data_generation/create_seg.py.
In divide_vert_into_bodypart() function, it uses 'scripts/3d/neutral_smpl_with_cocoplus_reg.pkl', I want to know what it is, and how can I get it. And this function doesn't seem to calculate seg of a image.

**Comment by xiezhy6** [comment]
@ly015 
Hi，is there something wrong in line172 of `./script/data_generation/create_seg.py`? It seems like the `hmr_pts` is calculated from` joint_lable_hmr` not from `joint_label`.

**Comment by xiezhy6** [comment]
> Hi, thanks for your great work. I want to know how to generate seg labels. I read code in data_generation/create_seg.py.
> In divide_vert_into_bodypart() function, it uses 'scripts/3d/neutral_smpl_with_cocoplus_reg.pkl', I want to know what it is, and how can I get it. And this function doesn't seem to calculate seg of a image.

In this code, calculating segmentation is done in function `create_silhouette`.  And the `neutral_smpl_with_cocoplus_reg.pkl'` can be found in HMR repository.

**Comment by ly015** [comment]
@xiezhy6 Yes, that is a mistake. The code has been corrected and the data will be checked. Thank you.

**Comment by Lotayou** [comment]
@SeaOfOcean Hi I'm working on testing the pretrained model but cannot get around the feature extraction part... Can you help me by detailing the steps I need to do to prepare all necessary ground truth annotations before running the testing script? Thanks!
