### ISSUE TITLE
What is the variable d?

### ISSUE THREAD

**Issue by cfanyyx** [ly015/intrinsic_flow#9]
Thanks for sharing your brilliant codes.
Here is a question. What is the variable d in line 146 of 'data/pose_transfer_dataset.py'?

**Comment by ly015** [comment]
@cfanyyx "d" should be "joint_c_2", sorry for the typo.
Please also note that this code segment is for data augmentation, which is actually not used in our experiments. So its effect is unclear and may not be positive.
